name: 🧪 Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      # Step 1 — Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2 — Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Step 3 — Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4 — Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Step 5 — Run tests with multiple reporters
      # list: console summary
      # github: inline annotations for failed tests
      # html: full report for download/viewing
      - name: Run Playwright Tests
        run: npx playwright test --reporter=list,github,html

      # Step 6 — Upload HTML report artifact
      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  # Optional job: Publish the HTML report to GitHub Pages
  deploy-report:
    name: 📊 Deploy Test Report to GitHub Pages
    needs: test
    if: always() # always run even if tests fail
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: playwright-report
